1. Write a code that prints the numbers from 0 to 100, with the following conditions: 
- If the number is divisible by 3, print the string 'a' instead of the number. 
- If the number is divisible by 5, print the string 'b' instead of the number. 
- If the number is divisible by both 3 and 5, print the string 'ab' instead of the number.

In [16]:
for number in range(100):
    if number%3==0 and number%5==0:
        print("ab")
    elif number%3==0:
        print("a")
    elif number%5==0:
        print("b")
    else:
        print(number)


ab
1
2
a
4
b
a
7
8
a
b
11
a
13
14
ab
16
17
a
19
b
a
22
23
a
b
26
a
28
29
ab
31
32
a
34
b
a
37
38
a
b
41
a
43
44
ab
46
47
a
49
b
a
52
53
a
b
56
a
58
59
ab
61
62
a
64
b
a
67
68
a
b
71
a
73
74
ab
76
77
a
79
b
a
82
83
a
b
86
a
88
89
ab
91
92
a
94
b
a
97
98
a


2. Create a 3x3 2D array filled with random integers between 1 and 10 (inclusive) 
- Calculate and print the sum of each row 
- Find and print the maximum and minimum values in the matrix, along with their 
positions (row and column indices). 

In [35]:
from random import randint
import numpy as np

#make array
array_1 = np.array([[randint(1,10), randint(1,10), randint(1,10)],
                  [randint(1,10), randint(1,10), randint(1,10)],
                  [randint(1,10), randint(1,10), randint(1,10)]])

print(array_1)

# row sums
for row in array_1:
    print(sum(row))

#with positions
min_val =  (array_1.min(), np.where(array_1 == array_1.min()))
max_val = (array_1.max(), np.where(array_1 == array_1.max()))

print(f"The min is at {min_val} and the max is at {max_val}")


[[4 1 4]
 [4 3 7]
 [2 3 1]]
9
14
6
The min is at (1, (array([0, 2]), array([1, 2]))) and the max is at (7, (array([1]), array([2])))


3. Write a code that checks whether a given number x is part of the Fibonacci sequence. 
The program should output True if x is in the sequence and False otherwise.

In [50]:
import math

def isitasquare(test_number):
    square_root = int(math.sqrt(test_number))
    return square_root*square_root == test_number

test_number = 49
print(isitasquare(test_number))

# if a number is in the Fibonacci sequence, either 5𝑛2+45n2+4 or 5𝑛2−45n2−4 (or both) will be a perfect square
def isitafibonnaci(number):
    return isitasquare(5*number*number+4) or isitasquare(5*number*number - 4)

number = 15
if (isitafibonnaci(number) == True):
    print ("True")
else:
    print("False")

True
False


4. Write a program that: 
- Allows the user to provide a source folder, a destination folder, and a filename string 
in command line. 
- Copies all files from the source folder that starts with the filename string to the 
destination folder. 
- Need to be able to handle errors (wrong folder name, etc.). Return a message “Error” 
if any error occurs.

In [51]:
import argparse, os, shutil

parser = argparse.ArgumentParser()
parser.add_argument("source_folder")
parser.add_argument("destination_folder")
parser.add_argument("filename_string")
args = parser.parse_args()

try:
    for file in os.listdir(args.source_folder):
        if args.filename_string in file:
            shutil.copy(os.path.join(args.source_folder, file), args.destination_folder)
            found = True
    if not found:
        print(f"No files containing '{args.filename_string}' were found.")
except FileNotFoundError as e:
    if not os.path.exists(args.source_folder):
        print(f"Error: Source folder '{args.source_folder}' does not exist.")
    elif not os.path.exists(args.destination_folder):
        print(f"Error: Destination folder '{args.destination_folder}' does not exist.")
    else:
        print(f"File not found: {e}")

usage: ipykernel_launcher.py [-h] source_folder destination_folder file_name
ipykernel_launcher.py: error: the following arguments are required: source_folder, destination_folder, file_name


SystemExit: 2

/Users/elizabethnemeti/miniconda3/envs/SPR24ENV/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3516: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
